version: "3.1"

services:
  server:
    restart: on-failure
    container_name: project-s-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - DB_HOST=project-s-db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=ucare
      - DB_PORT=5432
      - SUPA_API_KEY=${SUPA_API_KEY}
      - SUPA_API_URL=${SUPA_API_URL}
      - SUPA_BUCKET_NAME=${SUPA_BUCKET_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_MODEL=http://project-s-model:8000
      - SENDING_EMAIL=${SENDING_EMAIL}
      - SENDING_PASSWORD=${SENDING_PASSWORD}
    ports:
      - "${PORT}:${PORT}"

  postgres:
    image: pgvector/pgvector:pg15
    restart: on-failure
    container_name: project-s-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ucare
    volumes:
      - ./databasepg:/var/lib/postgresql/data

  model:
    image: narutchai001/ucare-model:v2
    container_name: project-s-model
    ports:
      - "5000:8000"
