# Choose whatever you want, version >= 1.16
FROM golang:1.23-alpine


ARG PORT
ARG DB_HOST
ARG DB_USER
ARG DB_PASS
ARG DB_NAME
ARG DB_PORT
ARG SUPA_API_URL
ARG SUPA_API_KEY
ARG SUPA_BUCKET_NAME
ARG JWT_SECRET_KEY
ARG API_MODEL
ARG SENDING_EMAIL
ARG EMAIL_PASSWORD

ENV PORT=${PORT}
ENV DB_HOST=${DB_HOST}
ENV DB_USER=${DB_USER}
ENV DB_PASS=${DB_PASS}
ENV DB_NAME=${DB_NAME}
ENV DB_PORT=${DB_PORT}
ENV SUPA_API_URL=${SUPA_API_URL}
ENV SUPA_API_KEY=${SUPA_API_KEY}
ENV SUPA_BUCKET_NAME=${SUPA_BUCKET_NAME}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV API_MODEL=${API_MODEL}
ENV SENDING_EMAIL=${SENDING_EMAIL}
ENV EMAIL_PASSWORD=${EMAIL_PASSWORD}

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .




CMD ["air"]