basePath: /api
definitions:
  entities.Admin:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
    type: object
  presentation.Responses:
    properties:
      data: {}
      error: {}
      status:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for Project S.
  title: Project S API
  version: "1.0"
paths:
  /admin/login:
    post:
      consumes:
      - application/json
      description: Log in
      parameters:
      - description: Admin Object
        in: body
        name: admin
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentation.Responses'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presentation.Responses'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presentation.Responses'
      summary: Log in
      tags:
      - admin
  /admin/manage:
    get:
      consumes:
      - application/json
      description: Get admins
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentation.Responses'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presentation.Responses'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presentation.Responses'
      summary: Get admins
      tags:
      - admin
  /admin/manage/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an admin by ID
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/presentation.Responses'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presentation.Responses'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presentation.Responses'
      summary: Delete an admin by ID
      tags:
      - admin
    get:
      consumes:
      - application/json
      description: Get an admin by ID
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentation.Responses'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presentation.Responses'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presentation.Responses'
      summary: Get an admin by ID
      tags:
      - admin
    put:
      consumes:
      - application/json
      description: Update an admin by ID
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      - description: Admin Object
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/entities.Admin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presentation.Responses'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presentation.Responses'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presentation.Responses'
      summary: Update an admin by ID
      tags:
      - admin
swagger: "2.0"
